[package]
name = "tower"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-segmentation = "1.10.1"
im = "15.1.0"
unicode-xid = "0.2.4"
llvm-sys = { version = "180.0.0", features = [ "prefer-static" ] }
